routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//Route::group(['middlewareGroup' => 'webGroup'],function(){

//    Route::get('/','LoginController@login')->name('login');
//    Route::get('/login','LoginController@login');
//    Route::post('/login','LoginController@dologin')->name('admin.login');
//    Route::get('/logout','LoginController@logout')->name('logout');
Auth::routes();


Route::group(['middleware'=>'auth'],function(){

    Route::get('/home', 'HomeController@index');
Route::resource('/home/users','UserController');
//Route::resources('/home/attendance','AttendanceController');
Route::resource('/home/companies','CompaniesController');
Route::resource('/home/attendance','AttendanceController');
Route::resource('/home/holidays','HolidaysController');
Route::resource('/home/roles','RoleController');
Route::resource('/home/notices','NoticeController');
Route::resource('/home/leaves','LeavesController');
Route::resource('/movements','MovementsController');
//Route::resource('/holidays','HolidaysController');

    });
//});

app/Notices.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notices extends Model
{
    //
    protected $fillable=[
        'image','title','date','location','description'
    ];
}

app/Http/Controllers/NoticeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Notices;
use DB;

class NoticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $send=Notices::all();
        return view('notice.index',compact('send'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('notice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input=$request->all();
        if ($file=$request->file('image')){
            $name=$file->getClientOriginalName();
            $file->move('image',$name);
            $input['image']=$name;
        }
        Notices::create($input);


        return redirect('/home/notices');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function notice(){
        $send=Notices::all();
        return response()->json($send);

    }
    public function notice_show($id)
    {
        $noticeId=$id;
        $notice = DB::table('notices')
            ->select('id','title','description','date','image','location')
            ->where('id',$noticeId)
            ->get();
        if(is_null($notice))
        {
            $data = [
                "StatusCode" => 200,
                "Success" =>false,
                "Message"=>'No notice Found'
            ];
            return response($data,200);
        }else {
            $response = [
                "StatusCode" => 200,
                "Success" => true,
                "Message" => 'Notice Details Found',
                'notice detail' => $notice,
            ];
            return $response;
        }
    }
}

resources/views/notice/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                <form class="form-horizontal" method="post" enctype="multipart/form-data" action="/home/notices">
                    {{csrf_field()}}
                <div class="form-group">
                    <label for="image" class="col-sm-2 control-label">Image</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" name="image" >
                    </div>
                </div>
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="title" >
                    </div>
                </div>
                <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="description" >
                    </div>
                </div>
                <div class="form-group">
                    <label for="date" class="col-sm-2 control-label">date</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" name="date" >
                    </div>
                </div>
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" name="submit" value="Submit" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/notice/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1><a href="{{route('notices.create')}}"> Add Notice</a></h1>
                <table class="table-striped table-bordered table-condensed">
                    <th>Title</th>
                    <th>Image</th>
                    <th>Date</th>
                    @foreach($send as $a)
                        <tr>
                            <td>{{$a->title}}</td>
                            <td><div class="tbimg"><img src="/image/{{$a->image}}"></div></td>
                            <td>{{$a->date}}</td>
                            <td><a href="{{route('notices.edit',$a->id)}}"><button class="btn btn-primary">Edit</button></a></td>
                        </tr>
                        @endforeach
                </table>
            </div>
        </div>
    </div>
@endsection